"""
涛割 - 配置模块
"""

from .settings import (
    AppSettings,
    APIConfig,
    CreditSettings,
    UISettings,
    ExportSettings,
    GenerationSettings,
    ModelType,
    TaskStatus,
    GenerationMode,
    SettingsManager,
    get_settings,
    get_settings_manager,
)

from .constants import (
    EXPRESSION_LIBRARY,
    LEFT_HAND_ACTIONS,
    RIGHT_HAND_ACTIONS,
    BOTH_HANDS_ACTIONS,
    PLOT_ACTION_MAPPING,
    TAG_GENERATION_PROMPT,
    ACTION_ANALYSIS_PROMPT,
    IMAGE_GENERATION_PROMPT,
    VIDEO_GENERATION_PROMPT,
    TAG_CATEGORIES,
    TAG_CATEGORY_COLORS,
    TAG_FONT_COLORS,
    VIDEO_ASPECT_RATIOS,
    CAMERA_MOTIONS,
    TRANSITIONS,
    MODEL_CAPABILITIES,
    JIANYING_PLATFORM_INFO,
    SUPPORTED_IMAGE_EXTENSIONS,
    SUPPORTED_VIDEO_EXTENSIONS,
)

__all__ = [
    # Settings
    'AppSettings',
    'APIConfig',
    'CreditSettings',
    'UISettings',
    'ExportSettings',
    'GenerationSettings',
    'ModelType',
    'TaskStatus',
    'GenerationMode',
    'SettingsManager',
    'get_settings',
    'get_settings_manager',
    # Constants
    'EXPRESSION_LIBRARY',
    'LEFT_HAND_ACTIONS',
    'RIGHT_HAND_ACTIONS',
    'BOTH_HANDS_ACTIONS',
    'PLOT_ACTION_MAPPING',
    'TAG_GENERATION_PROMPT',
    'ACTION_ANALYSIS_PROMPT',
    'IMAGE_GENERATION_PROMPT',
    'VIDEO_GENERATION_PROMPT',
    'TAG_CATEGORIES',
    'TAG_CATEGORY_COLORS',
    'TAG_FONT_COLORS',
    'VIDEO_ASPECT_RATIOS',
    'CAMERA_MOTIONS',
    'TRANSITIONS',
    'MODEL_CAPABILITIES',
    'JIANYING_PLATFORM_INFO',
    'SUPPORTED_IMAGE_EXTENSIONS',
    'SUPPORTED_VIDEO_EXTENSIONS',
]
